#include "ac_ir.h"

#include <stdlib.h>

#include "driver/rmt_tx.h"
#include "esp_check.h"
#include "esp_log.h"
#include <string.h>
#include "driver/gpio.h"
#define TAG "ac_ir"

#define AC_IR_TX_GPIO           10

#define AC_IR_RESOLUTION_HZ    1000000
#define AC_IR_CARRIER_FREQ_HZ  38000
#define AC_IR_CARRIER_DUTY     0.33f

/*
 * Number of RMT symbols generated in one batch.
 *
 * The ESP32-C3 RMT memory is limited, so the custom encoder
 * generates a small batch and lets the RMT driver consume it.
 */
#define AC_IR_ENCODER_SYMBOLS   48


typedef struct {
    rmt_encoder_t base;

    /*
     * Primitive encoder used to copy generated RMT symbols
     * into the RMT driver's memory.
     */
    rmt_encoder_handle_t copy_encoder;

    /*
     * Current RMT symbol in the ac_ir_frame_t.
     *
     * symbol 0 -> durations[0], durations[1]
     * symbol 1 -> durations[2], durations[3]
     * symbol 2 -> durations[4], durations[5]
     * ...
     */
    size_t symbol_index;

    /*
     * Temporary RMT symbols generated by this encoder.
     */
    rmt_symbol_word_t symbols[AC_IR_ENCODER_SYMBOLS];

} ac_ir_encoder_t;


/* -------------------------------------------------------------------------- */
/* Module state                                                               */
/* -------------------------------------------------------------------------- */

static rmt_channel_handle_t s_tx_channel = NULL;
static rmt_encoder_handle_t s_encoder = NULL;

//debug

typedef struct {
    uint32_t symbol_index_before;
    uint32_t symbol_index_after;
    uint32_t symbol_count;
    uint32_t total_symbols;
    uint32_t written;
    uint32_t encoded_symbols;
    uint32_t copy_state;
    uint32_t state;
    uintptr_t enc_address;
    uint8_t memfull;
    uint8_t en_complete;
    uint8_t return_n;

    uint16_t d0[4];
    uint16_t d1[4];
} encode_debug_t;

static volatile encode_debug_t dbg[8];
static volatile uint32_t dbg_count = 0;
static volatile uint32_t dbg_encode_calls = 0;



/* -------------------------------------------------------------------------- */
/* Custom RMT encoder                                                        */
/* -------------------------------------------------------------------------- */

/* -------------------------------------------------------------------------- */
/* Custom RMT encoder                                                        */
/* -------------------------------------------------------------------------- */

/* -------------------------------------------------------------------------- */
/* Custom RMT encoder                                                        */
/* -------------------------------------------------------------------------- */

/* -------------------------------------------------------------------------- */
/* Custom RMT encoder                                                        */
/* -------------------------------------------------------------------------- */

static size_t IRAM_ATTR ac_ir_encoder_encode(
    rmt_encoder_t *encoder,
    rmt_channel_handle_t channel,
    const void *primary_data,
    size_t data_size,
    rmt_encode_state_t *ret_state)
{

    dbg_encode_calls++;

    ac_ir_encoder_t *enc = __containerof(encoder, ac_ir_encoder_t, base);
    const ac_ir_frame_t *frame = (const ac_ir_frame_t *)primary_data;

    rmt_encode_state_t copy_state = RMT_ENCODING_RESET;
    rmt_encode_state_t state = RMT_ENCODING_RESET;

    if (frame == NULL || data_size != sizeof(ac_ir_frame_t) || 
        frame->durations == NULL || frame->count == 0) {
        *ret_state = RMT_ENCODING_COMPLETE;
        return 0;
    }

    size_t total_symbols = (frame->count + 1) / 2;

    if (enc->symbol_index >= total_symbols) {
        *ret_state = RMT_ENCODING_COMPLETE;
        return data_size;
    }

    size_t remaining_symbols = total_symbols - enc->symbol_index;
    size_t symbol_count = remaining_symbols;

    if (symbol_count > AC_IR_ENCODER_SYMBOLS) {
        symbol_count = AC_IR_ENCODER_SYMBOLS;
    }

    for (size_t i = 0; i < symbol_count; i++) {
        size_t symbol_index = enc->symbol_index + i;
        size_t duration_index = symbol_index * 2;

        enc->symbols[i].level0 = 1;
        enc->symbols[i].duration0 = frame->durations[duration_index];

        enc->symbols[i].level1 = 0;
        if ((duration_index + 1) < frame->count) {
            enc->symbols[i].duration1 = frame->durations[duration_index + 1];
        } else {
            enc->symbols[i].duration1 = 0;
        }
    }

    
    size_t before = enc->symbol_index;

    size_t written = enc->copy_encoder->encode(
        enc->copy_encoder,
        channel,
        enc->symbols,
        symbol_count * sizeof(rmt_symbol_word_t),
        &copy_state
    );

    /* 
     * FINAL FIX: 'written' is ALREADY in RMT symbols.
     * DO NOT divide by sizeof(rmt_symbol_word_t) here! 
     * Dividing it caused the infinite loop and 306-bit garbage frame.
     */
    size_t encoded_symbols = written;// / sizeof(rmt_symbol_word_t);
    enc->symbol_index += encoded_symbols;


    

    if (copy_state & RMT_ENCODING_MEM_FULL) {
        dbg[dbg_count].memfull = 1;
        state |= RMT_ENCODING_MEM_FULL;
    }

    if (enc->symbol_index >= total_symbols) {
        dbg[dbg_count].en_complete = 1;
        state |= RMT_ENCODING_COMPLETE;
    }


    //toggle the debug gpio
    gpio_set_level(4,!gpio_get_level(4));


    if (dbg_count < 8) {
        dbg[dbg_count].symbol_index_before = before;
        dbg[dbg_count].symbol_index_after = enc->symbol_index;
        dbg[dbg_count].symbol_count = symbol_count;
        dbg[dbg_count].total_symbols = total_symbols;
        dbg[dbg_count].written = written;
        dbg[dbg_count].encoded_symbols = encoded_symbols;
        dbg[dbg_count].copy_state = copy_state;
        dbg[dbg_count].state = 0;   // fill after state calculation if desired
        dbg[dbg_count].enc_address = (uintptr_t)enc;

        if (dbg_count < 8) {
    
            for (int i = 0; i < 4 && i < symbol_count; i++) {
                dbg[dbg_count].d0[i] = enc->symbols[i].duration0;
                dbg[dbg_count].d1[i] = enc->symbols[i].duration1;
            }
        }

        dbg_count++;
    }





    if (state & RMT_ENCODING_COMPLETE) {
        dbg[dbg_count-1].return_n=1;
        *ret_state = state;
        return data_size; 


    }

    *ret_state = state;
    return 0;
}
/* -------------------------------------------------------------------------- */

static esp_err_t IRAM_ATTR ac_ir_encoder_reset(
    rmt_encoder_t *encoder)
{
    ac_ir_encoder_t *enc =
        __containerof(
            encoder,
            ac_ir_encoder_t,
            base
        );

    /*
     * Start the next transaction from the first symbol.
     */
    enc->symbol_index = 0;

    /*
     * The copy encoder is stateful as well, so reset it too.
     */
    return rmt_encoder_reset(
        enc->copy_encoder
    );
}


/* -------------------------------------------------------------------------- */
/* Encoder deletion                                                           */
/* -------------------------------------------------------------------------- */

static esp_err_t ac_ir_encoder_delete(
    rmt_encoder_t *encoder)
{
    ac_ir_encoder_t *enc =
        __containerof(
            encoder,
            ac_ir_encoder_t,
            base
        );

    if (enc->copy_encoder != NULL) {
        rmt_del_encoder(enc->copy_encoder);
        enc->copy_encoder = NULL;
    }

    free(enc);

    return ESP_OK;
}


/* -------------------------------------------------------------------------- */
/* Encoder creation                                                           */
/* -------------------------------------------------------------------------- */

static esp_err_t ac_ir_encoder_create(
    rmt_encoder_handle_t *ret_encoder)
{
    if (ret_encoder == NULL) {
        return ESP_ERR_INVALID_ARG;
    }

    ac_ir_encoder_t *encoder =
        calloc(
            1,
            sizeof(ac_ir_encoder_t)
        );

    if (encoder == NULL) {
        return ESP_ERR_NO_MEM;
    }


    encoder->base.encode =
        ac_ir_encoder_encode;

    encoder->base.reset =
        ac_ir_encoder_reset;

    encoder->base.del =
        ac_ir_encoder_delete;


    /*
     * The copy encoder configuration is currently an empty
     * reserved structure in ESP-IDF.
     */
    rmt_copy_encoder_config_t copy_config = {};

    esp_err_t ret =
        rmt_new_copy_encoder(
            &copy_config,
            &encoder->copy_encoder
        );

    if (ret != ESP_OK) {
        free(encoder);
        return ret;
    }


    encoder->symbol_index = 0;

    *ret_encoder =
        &encoder->base;

    return ESP_OK;
}


/* -------------------------------------------------------------------------- */
/* IR transmitter initialization                                              */
/* -------------------------------------------------------------------------- */

esp_err_t ac_ir_init(void)
{
    if (s_tx_channel != NULL) {
        return ESP_OK;
    }

    //For debugging will toggle on each ir transaction
       gpio_config_t io_conf_dbg1 = {
        .pin_bit_mask = 1ULL << 4,
        .mode = GPIO_MODE_INPUT_OUTPUT,
        .pull_up_en = GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type = GPIO_INTR_DISABLE,
    };

    ESP_ERROR_CHECK(
        gpio_config(&io_conf_dbg1)
    );

    gpio_config_t io_conf_dbg2 = {
        .pin_bit_mask = 1ULL << 3,
        .mode = GPIO_MODE_OUTPUT,
        .pull_up_en = GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type = GPIO_INTR_DISABLE,
    };

    ESP_ERROR_CHECK(
        gpio_config(&io_conf_dbg2)
    );

    //Changed here and also toggled in encode cb
    gpio_set_level(4,0);
    //changed here only Juist to confirm which settings are applied here
    gpio_set_level(3,0);


    rmt_tx_channel_config_t tx_config = {
        .clk_src = RMT_CLK_SRC_DEFAULT,

        /*
         * 1 tick = 1 us.
         *
         * This lets the protocol layer express all timings
         * directly in microseconds.
         */
        .resolution_hz =
            AC_IR_RESOLUTION_HZ,

        /*
         * ESP32-C3 RMT memory.
         *
         * The encoder handles frames larger than this by
         * continuing over multiple encode() calls.
         */
        .mem_block_symbols = 80,

        .trans_queue_depth = 1,

        .gpio_num =
            AC_IR_TX_GPIO,
    };


    esp_err_t ret =
        rmt_new_tx_channel(
            &tx_config,
            &s_tx_channel
        );

    if (ret != ESP_OK) {

        ESP_LOGE(
            TAG,
            "Failed to create RMT TX channel: %s",
            esp_err_to_name(ret)
        );

        return ret;
    }


    /*
     * Hardware-generated 38 kHz IR carrier.
     */
    rmt_carrier_config_t carrier_config = {
        .frequency_hz =
            AC_IR_CARRIER_FREQ_HZ,

        .duty_cycle =
            AC_IR_CARRIER_DUTY,
    };


 
    
    /*
    ret =
        rmt_apply_carrier(
            s_tx_channel,
            &carrier_config
        );
    */

    if (ret != ESP_OK) {

        ESP_LOGE(
            TAG,
            "Failed to configure IR carrier: %s",
            esp_err_to_name(ret)
        );

        rmt_del_channel(
            s_tx_channel
        );

        s_tx_channel = NULL;

        return ret;
    }


    /*
     * Create our protocol-independent waveform encoder.
     */
    ret =
        ac_ir_encoder_create(
            &s_encoder
        );

    if (ret != ESP_OK) {

        ESP_LOGE(
            TAG,
            "Failed to create IR encoder: %s",
            esp_err_to_name(ret)
        );

        rmt_del_channel(
            s_tx_channel
        );

        s_tx_channel = NULL;

        return ret;
    }


    ret =
        rmt_enable(
            s_tx_channel
        );

    if (ret != ESP_OK) {

        ESP_LOGE(
            TAG,
            "Failed to enable RMT TX: %s",
            esp_err_to_name(ret)
        );

        rmt_del_encoder(
            s_encoder
        );

        s_encoder = NULL;

        rmt_del_channel(
            s_tx_channel
        );

        s_tx_channel = NULL;

        return ret;
    }


    return ESP_OK;
}


/* -------------------------------------------------------------------------- */
/* IR transmission                                                            */
/* -------------------------------------------------------------------------- */

esp_err_t ac_ir_send(
    const ac_ir_frame_t *frame)
{
    if (frame == NULL ||
        frame->durations == NULL ||
        frame->count == 0) {

        return ESP_ERR_INVALID_ARG;
    }


    //memset(dbg, 0, sizeof(dbg)*8);
    dbg_count = 0;
    dbg_encode_calls = 0;
    //memfull=0;
    //en_complete=0;
    //return_n=0;
   

    if (s_tx_channel == NULL ||
        s_encoder == NULL) {

        return ESP_ERR_INVALID_STATE;
    }


    ESP_LOGI(TAG, "count=%u", frame->count);

    
    for (size_t i = 0; i < frame->count; i++) {
        ESP_LOGI(TAG, "duration[%u] = %u",
                (unsigned)i,
                frame->durations[i]);
    }
    /*
     * One-shot transmission.
     */
    rmt_transmit_config_t tx_config = {
        .loop_count = 0,
    };


    ESP_LOGI(TAG, "=== fu ===");
    esp_err_t ret =
        rmt_transmit(
            s_tx_channel,
            s_encoder,
            frame,
            sizeof(*frame),
            &tx_config
        );

    ESP_LOGI(TAG, "=== fu again===");
    if (ret != ESP_OK) {

        ESP_LOGI(
            TAG,
            "Failed to start RMT TX: %s",
            esp_err_to_name(ret)
        );
        return ret;
    }


    /*
     * Make the public API synchronous.
     *
     * The caller returns only after the complete IR waveform
     * has physically finished transmitting.
     */
    
    esp_err_t rett= rmt_tx_wait_all_done(
        s_tx_channel,
        5000
    );

    ESP_LOGI(TAG, "=== ENCODER TRACE === %d",dbg_count);

        for (uint32_t i = 0; i < dbg_count && i < 8; i++) {
            ESP_LOGI(TAG,
                    "call[%u]: enc=%p before=%u count=%u total=%u ,written=%u encoded=%u after=%u copy=0x%x state=0x%x, memfull %d, en_complete %d, return_n %d",
                    i,
                    (void *)dbg[i].enc_address,
                    dbg[i].symbol_index_before,
                    dbg[i].symbol_count,
                    dbg[i].total_symbols,
                    dbg[i].written,
                    dbg[i].encoded_symbols,
                    dbg[i].symbol_index_after,
                    dbg[i].copy_state,
                    dbg[i].state,
                    dbg[i].memfull,
                    dbg[i].en_complete, 
                    dbg[i].return_n);

        }

    ESP_LOGI(TAG, "ENCODER CALL COUNT = %u",
         (unsigned)dbg_encode_calls);

    return rett;

}


