#include "ac_ir.h"

#include <stdlib.h>

#include "driver/rmt_tx.h"
#include "esp_check.h"
#include "esp_log.h"

#define TAG "ac_ir"

#define AC_IR_TX_GPIO           10

#define AC_IR_RESOLUTION_HZ    1000000
#define AC_IR_CARRIER_FREQ_HZ  38000
#define AC_IR_CARRIER_DUTY     0.33f

/*
 * Number of RMT symbols generated in one batch.
 *
 * The ESP32-C3 RMT memory is limited, so the custom encoder
 * generates a small batch and lets the RMT driver consume it.
 */
#define AC_IR_ENCODER_SYMBOLS   32


typedef struct {
    rmt_encoder_t base;

    /*
     * Primitive encoder used to copy generated RMT symbols
     * into the RMT driver's memory.
     */
    rmt_encoder_handle_t copy_encoder;

    /*
     * Current RMT symbol in the ac_ir_frame_t.
     *
     * symbol 0 -> durations[0], durations[1]
     * symbol 1 -> durations[2], durations[3]
     * symbol 2 -> durations[4], durations[5]
     * ...
     */
    size_t symbol_index;

    /*
     * Temporary RMT symbols generated by this encoder.
     */
    rmt_symbol_word_t symbols[AC_IR_ENCODER_SYMBOLS];

} ac_ir_encoder_t;


/* -------------------------------------------------------------------------- */
/* Module state                                                               */
/* -------------------------------------------------------------------------- */

static rmt_channel_handle_t s_tx_channel = NULL;
static rmt_encoder_handle_t s_encoder = NULL;

//debug

typedef struct {
    uint32_t symbol_index_before;
    uint32_t symbol_index_after;
    uint32_t symbol_count;
    uint32_t total_symbols;
    uint32_t written;
    uint32_t encoded_symbols;
    uint32_t copy_state;
    uint32_t state;
    uintptr_t enc_address;
} encode_debug_t;

static volatile encode_debug_t dbg[8];
static volatile uint32_t dbg_count = 0;
static volatile uint32_t dbg_encode_calls = 0;
/* -------------------------------------------------------------------------- */
/* Custom RMT encoder                                                        */
/* -------------------------------------------------------------------------- */

static size_t IRAM_ATTR ac_ir_encoder_encode(
    rmt_encoder_t *encoder,
    rmt_channel_handle_t channel,
    const void *primary_data,
    size_t data_size,
    rmt_encode_state_t *ret_state)
{
    dbg_encode_calls++;
    ac_ir_encoder_t *enc =
        __containerof(encoder, ac_ir_encoder_t, base);

    const ac_ir_frame_t *frame =
        (const ac_ir_frame_t *)primary_data;

    rmt_encode_state_t copy_state =
        RMT_ENCODING_RESET;

    rmt_encode_state_t state =
        RMT_ENCODING_RESET;

    /*
     * Validate the input expected by this encoder.
     *
     * This function runs in the RMT encoding path, so don't
     * call anything that can block here.
     */
    if (frame == NULL ||
        data_size != sizeof(ac_ir_frame_t) ||
        frame->durations == NULL ||
        frame->count == 0) {

        *ret_state = RMT_ENCODING_COMPLETE;
        return 0;
    }

    /*
     * Calculate how many RMT symbols remain.
     *
     * Two durations make one RMT symbol:
     *
     *     duration[0] = MARK
     *     duration[1] = SPACE
     *
     * Therefore an odd final duration is also supported.
     */
    size_t total_symbols =
        (frame->count + 1) / 2;

    if (enc->symbol_index >= total_symbols) {
        *ret_state = RMT_ENCODING_COMPLETE;
        return 0;
    }

    size_t remaining_symbols =
        total_symbols - enc->symbol_index;

    size_t symbol_count =
        remaining_symbols;

    if (symbol_count > AC_IR_ENCODER_SYMBOLS) {
        symbol_count = AC_IR_ENCODER_SYMBOLS;
    }


    /*
     * Convert the protocol's mark/space durations into
     * RMT symbols.
     */
    for (size_t i = 0; i < symbol_count; i++) {

        size_t symbol_index =
            enc->symbol_index + i;

        size_t duration_index =
            symbol_index * 2;


        /*
         * MARK
         *
         * RMT carrier is enabled by the channel during this
         * portion because level0 = 1.
         */
        enc->symbols[i].level0 = 1;

        enc->symbols[i].duration0 =
            frame->durations[duration_index];


        /*
         * SPACE
         *
         * Carrier is disabled because level1 = 0.
         */
        enc->symbols[i].level1 = 0;


        if ((duration_index + 1) < frame->count) {

            enc->symbols[i].duration1 =
                frame->durations[duration_index + 1];

        } else {

            /*
             * The protocol ended with a MARK and therefore
             * has no following SPACE.
             */
            enc->symbols[i].duration1 = 0;
        }
    }


    uint32_t debug_slot = dbg_count;

    if (debug_slot < 8) {
        dbg[debug_slot].symbol_index_before = enc->symbol_index;
        dbg[debug_slot].symbol_count = symbol_count;
        dbg[debug_slot].total_symbols = total_symbols;
        dbg[debug_slot].enc_address = (uintptr_t)enc;
    }
            /*
     * Ask the copy encoder to put the generated symbols into
     * the RMT driver's available memory.
     */
    size_t written =
        enc->copy_encoder->encode(
            enc->copy_encoder,
            channel,
            enc->symbols,
            symbol_count * sizeof(rmt_symbol_word_t),
            &copy_state
        );

    size_t encoded_symbols = written;// / sizeof(rmt_symbol_word_t);
    enc->symbol_index += encoded_symbols;

    if (debug_slot < 8) {
        dbg[debug_slot].symbol_index_after = enc->symbol_index;
    }

    if (debug_slot < 8) {
        dbg[debug_slot].written = written;
        dbg[debug_slot].encoded_symbols = encoded_symbols;
        dbg[debug_slot].copy_state = copy_state;
    }

    enc->symbol_index += encoded_symbols;

    if (debug_slot < 8) {
        dbg[debug_slot].state = state;
        dbg_count++;
    }

    /*
     * IMPORTANT FIX:
     * The copy encoder returns the number of BYTES written.
     * We must convert this back to the number of symbols to
     * advance our symbol_index correctly.
     */
    


    


    /*
     * Propagate the copy encoder's "memory full" condition.
     */
       /*
     * Propagate the copy encoder's "memory full" condition.
     */
    if (copy_state & RMT_ENCODING_MEM_FULL) {
        state |= RMT_ENCODING_MEM_FULL;
    }

    /*
     * We have encoded the entire frame.
     */
    if (enc->symbol_index >= total_symbols) {
        state |= RMT_ENCODING_COMPLETE;
        
        /*
         * IMPORTANT FIX:
         * Return data_size to tell the RMT driver we have
         * consumed the entire primary_data payload. 
         * This breaks the RMT driver's internal while loop 
         * and prevents a Watchdog reboot!
         */
        *ret_state = state;
        return data_size;
    }

    *ret_state = state;

    /*
     * Return 0 because we are NOT consuming primary_data 
     * sequentially. Returning 0 tells the driver: "I haven't 
     * consumed the primary_data payload, use my state flags instead."
     */
    return 0;
}


/* -------------------------------------------------------------------------- */
/* Encoder reset                                                              */
/* -------------------------------------------------------------------------- */

static esp_err_t IRAM_ATTR ac_ir_encoder_reset(
    rmt_encoder_t *encoder)
{
    ac_ir_encoder_t *enc =
        __containerof(
            encoder,
            ac_ir_encoder_t,
            base
        );

    /*
     * Start the next transaction from the first symbol.
     */
    enc->symbol_index = 0;

    /*
     * The copy encoder is stateful as well, so reset it too.
     */
    return rmt_encoder_reset(
        enc->copy_encoder
    );
}


/* -------------------------------------------------------------------------- */
/* Encoder deletion                                                           */
/* -------------------------------------------------------------------------- */

static esp_err_t ac_ir_encoder_delete(
    rmt_encoder_t *encoder)
{
    ac_ir_encoder_t *enc =
        __containerof(
            encoder,
            ac_ir_encoder_t,
            base
        );

    if (enc->copy_encoder != NULL) {
        rmt_del_encoder(enc->copy_encoder);
        enc->copy_encoder = NULL;
    }

    free(enc);

    return ESP_OK;
}


/* -------------------------------------------------------------------------- */
/* Encoder creation                                                           */
/* -------------------------------------------------------------------------- */

static esp_err_t ac_ir_encoder_create(
    rmt_encoder_handle_t *ret_encoder)
{
    if (ret_encoder == NULL) {
        return ESP_ERR_INVALID_ARG;
    }

    ac_ir_encoder_t *encoder =
        calloc(
            1,
            sizeof(ac_ir_encoder_t)
        );

    if (encoder == NULL) {
        return ESP_ERR_NO_MEM;
    }


    encoder->base.encode =
        ac_ir_encoder_encode;

    encoder->base.reset =
        ac_ir_encoder_reset;

    encoder->base.del =
        ac_ir_encoder_delete;


    /*
     * The copy encoder configuration is currently an empty
     * reserved structure in ESP-IDF.
     */
    rmt_copy_encoder_config_t copy_config = {};

    esp_err_t ret =
        rmt_new_copy_encoder(
            &copy_config,
            &encoder->copy_encoder
        );

    if (ret != ESP_OK) {
        free(encoder);
        return ret;
    }


    encoder->symbol_index = 0;

    *ret_encoder =
        &encoder->base;

    return ESP_OK;
}


/* -------------------------------------------------------------------------- */
/* IR transmitter initialization                                              */
/* -------------------------------------------------------------------------- */

esp_err_t ac_ir_init(void)
{
    if (s_tx_channel != NULL) {
        return ESP_OK;
    }


    rmt_tx_channel_config_t tx_config = {
        .clk_src = RMT_CLK_SRC_DEFAULT,

        /*
         * 1 tick = 1 us.
         *
         * This lets the protocol layer express all timings
         * directly in microseconds.
         */
        .resolution_hz =
            AC_IR_RESOLUTION_HZ,

        /*
         * ESP32-C3 RMT memory.
         *
         * The encoder handles frames larger than this by
         * continuing over multiple encode() calls.
         */
        .mem_block_symbols = 48,

        .trans_queue_depth = 1,

        .gpio_num =
            AC_IR_TX_GPIO,
    };


    esp_err_t ret =
        rmt_new_tx_channel(
            &tx_config,
            &s_tx_channel
        );

    if (ret != ESP_OK) {

        ESP_LOGE(
            TAG,
            "Failed to create RMT TX channel: %s",
            esp_err_to_name(ret)
        );

        return ret;
    }


    /*
     * Hardware-generated 38 kHz IR carrier.
     */
    rmt_carrier_config_t carrier_config = {
        .frequency_hz =
            AC_IR_CARRIER_FREQ_HZ,

        .duty_cycle =
            AC_IR_CARRIER_DUTY,
    };


    ret =
        rmt_apply_carrier(
            s_tx_channel,
            &carrier_config
        );

    if (ret != ESP_OK) {

        ESP_LOGE(
            TAG,
            "Failed to configure IR carrier: %s",
            esp_err_to_name(ret)
        );

        rmt_del_channel(
            s_tx_channel
        );

        s_tx_channel = NULL;

        return ret;
    }


    /*
     * Create our protocol-independent waveform encoder.
     */
    ret =
        ac_ir_encoder_create(
            &s_encoder
        );

    if (ret != ESP_OK) {

        ESP_LOGE(
            TAG,
            "Failed to create IR encoder: %s",
            esp_err_to_name(ret)
        );

        rmt_del_channel(
            s_tx_channel
        );

        s_tx_channel = NULL;

        return ret;
    }


    ret =
        rmt_enable(
            s_tx_channel
        );

    if (ret != ESP_OK) {

        ESP_LOGE(
            TAG,
            "Failed to enable RMT TX: %s",
            esp_err_to_name(ret)
        );

        rmt_del_encoder(
            s_encoder
        );

        s_encoder = NULL;

        rmt_del_channel(
            s_tx_channel
        );

        s_tx_channel = NULL;

        return ret;
    }


    return ESP_OK;
}


/* -------------------------------------------------------------------------- */
/* IR transmission                                                            */
/* -------------------------------------------------------------------------- */

esp_err_t ac_ir_send(
    const ac_ir_frame_t *frame)
{
    if (frame == NULL ||
        frame->durations == NULL ||
        frame->count == 0) {

        return ESP_ERR_INVALID_ARG;
    }



   

    if (s_tx_channel == NULL ||
        s_encoder == NULL) {

        return ESP_ERR_INVALID_STATE;
    }


    ESP_LOGI(TAG, "count=%u", frame->count);

    for (size_t i = 0; i < frame->count; i++) {
        ESP_LOGI(TAG, "duration[%u] = %u",
                (unsigned)i,
                frame->durations[i]);
    }
    /*
     * One-shot transmission.
     */
    rmt_transmit_config_t tx_config = {
        .loop_count = 0,
    };


    ESP_LOGI(TAG, "=== fu ===");
    esp_err_t ret =
        rmt_transmit(
            s_tx_channel,
            s_encoder,
            frame,
            sizeof(*frame),
            &tx_config
        );

    ESP_LOGI(TAG, "=== fu again===");
    if (ret != ESP_OK) {

        ESP_LOGI(
            TAG,
            "Failed to start RMT TX: %s",
            esp_err_to_name(ret)
        );
        return ret;
    }


    /*
     * Make the public API synchronous.
     *
     * The caller returns only after the complete IR waveform
     * has physically finished transmitting.
     */
    
    esp_err_t rett= rmt_tx_wait_all_done(
        s_tx_channel,
        1000
    );

    ESP_LOGI(TAG, "=== ENCODER TRACE ===");

        for (uint32_t i = 0; i < dbg_count && i < 8; i++) {
            ESP_LOGI(TAG,
                    "call[%u]: enc=%p before=%u count=%u total=%u written=%u encoded=%u after=%u copy=0x%x state=0x%x",
                    i,
                    (void *)dbg[i].enc_address,
                    dbg[i].symbol_index_before,
                    dbg[i].symbol_count,
                    dbg[i].total_symbols,
                    dbg[i].written,
                    dbg[i].encoded_symbols,
                    dbg[i].symbol_index_after,
                    dbg[i].copy_state,
                    dbg[i].state);
        }

    ESP_LOGI(TAG, "ENCODER CALL COUNT = %u",
         (unsigned)dbg_encode_calls);

    return rett;

}